- models/data_test.go
- models/dbstatus_test.go
- models/log_test.go
- models/machine.go
- models/machine_test.go
> chore: add more tests

- models/config_test.go
- models/coordinators_test.go
- models/data_test.go
- models/dbstatus_test.go
- models/log_test.go
- models/process.go
- models/process_test.go
- models/qos_test.go
- models/workload_test.go
> chore: tests for all models

- db/conn.go
- metrics/group.go
- metrics/group_coordinators.go
- metrics/group_coordinators_test.go
- metrics/group_data.go
- metrics/group_data_test.go
- metrics/group_dbstatus.go
- metrics/group_dbstatus_test.go
- metrics/group_workload_bytes.go
- metrics/group_workload_bytes_test.go
- metrics/group_workload_keys.go
- metrics/group_workload_keys_test.go
- metrics/group_workload_operations.go
- metrics/group_workload_operations_test.go
- metrics/group_workload_transactions.go
- metrics/group_workload_transactions_test.go
- metrics/helpers.go
- metrics/metric_provider.go
- metrics/status.go
- metrics/testing.go
- test/data/moving-data.json
* Integration testing for metrics
* Ability to check for presence of tags in test
* Refactor the SetGauge functions to one
> integration testing for metrics

- db/conn.go
- metrics/group_processes.go
- metrics/group_processes_test.go
- metrics/helpers.go
- metrics/metric_provider.go
- metrics/status.go
- models/cluster.go
- util/log/log.go
Add metrics for individual processes.
> process metrics

- metrics/group_processes.go
Add more tagging based on the role of the processes.
> feat: tags by process roles

- metrics/group_processes.go
- models/process.go
Tag processes with their human readable names.
> feat: tag processes with their human readable name

- metrics/group_processes.go
Rename pod name to fdb pod name.
> chore: rename pod name to fdb_pod_name

- metrics/group_processes.go
Typo fix in cluster controller tag.
> chore: typo fix in cluster controller tag

- metrics/group_workload_keys.go
- metrics/group_workload_keys_test.go
> fix: workload keys metrics

- metrics/group_latency_probe.go
- metrics/group_latency_probe_test.go
- metrics/metric_provider.go
- metrics/status.go
> feat: add latency probes

- metrics/group_processes.go
- metrics/group_processes_test.go
- metrics/helpers.go
- models/client.go
- models/client_test.go
- models/cluster.go
- models/cluster_message.go
- models/cluster_test.go
- models/config.go
- models/config_test.go
- models/data.go
- models/data_test.go
- models/log.go
- models/log_test.go
- models/process.go
- models/qos.go
- models/qos_test.go
- models/workload.go
- models/workload_test.go
* Latency metrics per process
* Converted all int to int64
> feat: per process latency metrics

- models/process.go
Time can be float not just int.
> chore: fix process type

- metrics/group_backup.go
- metrics/group_backup_test.go
- metrics/metric_provider.go
- metrics/status.go
- models/backup.go
- models/backup_test.go
- models/cluster.go
- models/dr_backup.go
- models/dr_backup_test.go
- models/layers.go
- models/process_test.go
- test/data/backup-completed.json
- test/data/backup-running.json
- test/data/dr-backup-dest.json
- test/data/dr-backup-source.json
Basic monitoring capabilities for continuous backups. This is a starting point we can iterate from.
> feat: allow for basic monitoring of continuous backups

- metrics/group_backup.go
Fixes possible panic is backup section does not exist.
> fix: possible panic if backup section doesn't exist

- dashboards/exporter-dashboard.json
Add example grafana dashboard.
> add example grafana dashboard

- metrics/group_backup.go
Add metric for not configured backup.
> metric for not configured backup

- metrics/group_backup.go
- metrics/group_backup_test.go
add test for absent backup metric
> fix absent backup metric

- db/conn.go
- metrics/metric_provider.go
- metrics/metric_reporter.go
- metrics/scope.go
- util/log/log.go
Refactoring error returns a bit based on previous feedback
> refactor error returns a bit

- metrics/group_processes.go
- models/process.go
Add metric for degraded FoundationDB processes.
> add metric for degraded process

- metrics/group_backup_test.go
- metrics/metric_reporter.go
make backup reporting optional
> make backup reporting optional

- metrics/group_qos.go
- metrics/metric_reporter.go
- metrics/status.go
> Adding QOS metrics

- metrics/group_processes.go
Add grv counter metrics to the exported ones.
> add grv counter metrics
